// frontend/src/database/seeds/pole-inspection-data.ts

export const poleInspectionFields = [
  // I. General Information
  { SectionKey: "general_information", FieldName: "Date", FieldKey: "date", FieldType: "DATE_AUTO", Placeholder: null, DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 1, DisplayOrder: 1, IsVisible: 1, IsReadOnly: 0, IsSystemField: 1, DataSourceType: null, DataSource: null, Width: 12, Icon: "calendar" },
  { SectionKey: "general_information", FieldName: "Inspector Name", FieldKey: "inspector_name", FieldType: "text", Placeholder: "Enter Inspector Name", DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 1, DisplayOrder: 2, IsVisible: 1, IsReadOnly: 0, IsSystemField: 0, DataSourceType: null, DataSource: null, Width: 6, Icon: null },
  { SectionKey: "general_information", FieldName: "Division", FieldKey: "division", FieldType: "dropdown", Placeholder: "Select Division", DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 1, DisplayOrder: 3, IsVisible: 1, IsReadOnly: 0, IsSystemField: 0, DataSourceType: "project", DataSource: "Divisions", Width: 6, Icon: null },
  { SectionKey: "general_information", FieldName: "District", FieldKey: "district", FieldType: "dropdown", Placeholder: "Select District", DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 1, DisplayOrder: 4, IsVisible: 1, IsReadOnly: 0, IsSystemField: 0, DataSourceType: "project", DataSource: "Districts", Width: 6, Icon: null },
  { SectionKey: "general_information", FieldName: "Block", FieldKey: "block", FieldType: "text", Placeholder: "Enter Block", DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 0, DisplayOrder: 5, IsVisible: 1, IsReadOnly: 0, IsSystemField: 0, DataSourceType: null, DataSource: null, Width: 6, Icon: null },
  { SectionKey: "general_information", FieldName: "Site ID", FieldKey: "pole_id", FieldType: "text", Placeholder: "Enter Site ID", DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 1, DisplayOrder: 6, IsVisible: 1, IsReadOnly: 0, IsSystemField: 0, DataSourceType: null, DataSource: null, Width: 6, Icon: null },
  { SectionKey: "general_information", FieldName: "Location Address", FieldKey: "location", FieldType: "multiline", Placeholder: "Enter location address", DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 0, DisplayOrder: 7, IsVisible: 1, IsReadOnly: 0, IsSystemField: 0, DataSourceType: null, DataSource: null, Width: 12, Icon: null },
  { SectionKey: "general_information", FieldName: "Lat/Long", FieldKey: "gps", FieldType: "GPS", Placeholder: null, DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 1, DisplayOrder: 8, IsVisible: 1, IsReadOnly: 0, IsSystemField: 0, DataSourceType: null, DataSource: null, Width: 12, Icon: "map" },

  // II. Pole Structure
  { SectionKey: "pole_structure", FieldName: "Foundation Condition", FieldKey: "foundation_cond", FieldType: "dropdown", Placeholder: "Select Foundation Condition", DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 1, DisplayOrder: 1, IsVisible: 1, IsReadOnly: 0, IsSystemField: 0, DataSourceType: "options", DataSource: "foundation_cond", Width: 12, Icon: null },
  { SectionKey: "pole_structure", FieldName: "Pole Availability", FieldKey: "pole_avail", FieldType: "dropdown", Placeholder: "Select Pole Availability", DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 1, DisplayOrder: 2, IsVisible: 1, IsReadOnly: 0, IsSystemField: 0, DataSourceType: "options", DataSource: "pole_avail", Width: 12, Icon: null },
  { SectionKey: "pole_structure", FieldName: "Pole SI", FieldKey: "pole_si", FieldType: "dropdown", Placeholder: "Select Pole SI", DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 0, DisplayOrder: 3, IsVisible: 1, IsReadOnly: 0, IsSystemField: 0, DataSourceType: "options", DataSource: "pole_si", Width: 12, Icon: null },
  { SectionKey: "pole_structure", FieldName: "Pole Status", FieldKey: "pole_status", FieldType: "dropdown", Placeholder: "Select Pole Status", DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 0, DisplayOrder: 4, IsVisible: 1, IsReadOnly: 0, IsSystemField: 0, DataSourceType: "options", DataSource: "pole_status", Width: 12, Icon: null },

  // III. Junction Box
  { SectionKey: "junction_box", FieldName: "Junction Box Status", FieldKey: "jb_status", FieldType: "dropdown", Placeholder: "Select Junction Box Status", DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 1, DisplayOrder: 1, IsVisible: 1, IsReadOnly: 0, IsSystemField: 0, DataSourceType: "options", DataSource: "jb_status", Width: 12, Icon: null },
  { SectionKey: "junction_box", FieldName: "Power Cable", FieldKey: "power_cable", FieldType: "dropdown", Placeholder: "Select Power Cable", DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 0, DisplayOrder: 2, IsVisible: 1, IsReadOnly: 0, IsSystemField: 0, DataSourceType: "options", DataSource: "power_cable", Width: 12, Icon: null },
  { SectionKey: "junction_box", FieldName: "Power Cable Status", FieldKey: "cable_status", FieldType: "dropdown", Placeholder: "Select Cable Status", DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 0, DisplayOrder: 3, IsVisible: 1, IsReadOnly: 0, IsSystemField: 0, DataSourceType: "options", DataSource: "cable_status", Width: 12, Icon: null },
  { SectionKey: "junction_box", FieldName: "Power Cable Length", FieldKey: "cable_length", FieldType: "text", Placeholder: "Enter Cable Length", DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 0, DisplayOrder: 4, IsVisible: 1, IsReadOnly: 0, IsSystemField: 0, DataSourceType: null, DataSource: null, Width: 12, Icon: null },

  // IV. Earthing
  { SectionKey: "earthing", FieldName: "Earthing Wire", FieldKey: "earthing_wire", FieldType: "dropdown", Placeholder: "Select Earthing Wire Status", DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 0, DisplayOrder: 1, IsVisible: 1, IsReadOnly: 0, IsSystemField: 0, DataSourceType: "options", DataSource: "earthing_wire", Width: 12, Icon: null },
  { SectionKey: "earthing", FieldName: "Earthing Chamber", FieldKey: "earthing_chamber", FieldType: "dropdown", Placeholder: "Select Earthing Chamber Status", DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 0, DisplayOrder: 2, IsVisible: 1, IsReadOnly: 0, IsSystemField: 0, DataSourceType: "options", DataSource: "earthing_chamber", Width: 12, Icon: null },
  { SectionKey: "earthing", FieldName: "Earthing Cover", FieldKey: "earthing_cover", FieldType: "dropdown", Placeholder: "Select Earthing Cover Status", DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 0, DisplayOrder: 3, IsVisible: 1, IsReadOnly: 0, IsSystemField: 0, DataSourceType: "options", DataSource: "earthing_cover", Width: 12, Icon: null },
  { SectionKey: "earthing", FieldName: "Earthing Voltage", FieldKey: "earthing_voltage", FieldType: "text", Placeholder: "Enter Voltage", DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 0, DisplayOrder: 4, IsVisible: 1, IsReadOnly: 0, IsSystemField: 0, DataSourceType: null, DataSource: null, Width: 12, Icon: null },

  // V. Metering
  { SectionKey: "meter", FieldName: "Meter Box Status", FieldKey: "meter_box_status", FieldType: "dropdown", Placeholder: "Select Meter Box Status", DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 0, DisplayOrder: 1, IsVisible: 1, IsReadOnly: 0, IsSystemField: 0, DataSourceType: "options", DataSource: "meter_box_status", Width: 12, Icon: null },
  { SectionKey: "meter", FieldName: "Meter Status", FieldKey: "meter_status", FieldType: "dropdown", Placeholder: "Select Meter Status", DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 0, DisplayOrder: 2, IsVisible: 1, IsReadOnly: 0, IsSystemField: 0, DataSourceType: "options", DataSource: "meter_status", Width: 12, Icon: null },
  { SectionKey: "meter", FieldName: "Meter Power Status", FieldKey: "meter_power_status", FieldType: "dropdown", Placeholder: "Select Power Status", DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 0, DisplayOrder: 3, IsVisible: 1, IsReadOnly: 0, IsSystemField: 0, DataSourceType: "options", DataSource: "meter_power_status", Width: 12, Icon: null },
  { SectionKey: "meter", FieldName: "Meter Serial Number", FieldKey: "meter_serial", FieldType: "text", Placeholder: "Enter Meter Serial Number", DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 0, DisplayOrder: 4, IsVisible: 1, IsReadOnly: 0, IsSystemField: 0, DataSourceType: null, DataSource: null, Width: 12, Icon: null },

  // VI. Connectivity
  { SectionKey: "connectivity", FieldName: "Connectivity Type", FieldKey: "connectivity_type", FieldType: "dropdown", Placeholder: "Select Connectivity Type", DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 0, DisplayOrder: 1, IsVisible: 1, IsReadOnly: 0, IsSystemField: 0, DataSourceType: "options", DataSource: "connectivity_type", Width: 12, Icon: null },

  // VII. Camera
  { SectionKey: "camera_information", FieldName: "Camera Count", FieldKey: "camera_count", FieldType: "number", Placeholder: "Enter Camera Count", DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 1, DisplayOrder: 1, IsVisible: 1, IsReadOnly: 0, IsSystemField: 0, DataSourceType: null, DataSource: null, Width: 12, Icon: "camera" },

  // VIII. Switch
  { SectionKey: "switch_information", FieldName: "Switch Count", FieldKey: "switch_count", FieldType: "number", Placeholder: "Enter Switch Count", DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 0, DisplayOrder: 1, IsVisible: 1, IsReadOnly: 0, IsSystemField: 0, DataSourceType: null, DataSource: null, Width: 12, Icon: "git-network" },

  // IX. Remarks
  { SectionKey: "remarks", FieldName: "Remarks", FieldKey: "remarks", FieldType: "multiline", Placeholder: "Enter remarks or observations", DefaultValue: null, HelpText: null, ValidationRule: null, IsRequired: 0, DisplayOrder: 1, IsVisible: 1, IsReadOnly: 0, IsSystemField: 0, DataSourceType: null, DataSource: null, Width: 12, Icon: null }
];
